### PR TITLE
Update 0.9.3

### PR DESCRIPTION
**Pull request by sagikazarmark**
Updating manually until we have GoReleaser working.

### CODE REVIEW

**Review by kpenfound — APPROVED** [review]
LGTM

**Review by kpenfound — APPROVED** [review]
LGTMTM

**Review by jpadams — APPROVED** [review]
LGTM!

**Comment by gerhard** [comment]
You now are @jpadams & @kpenfound! Same as all other @dagger/maintainers 💪

**Review by gerhard — APPROVED** [review]
🚀

**Pull request merged**
